### ISSUE TITLE
`setCollectAndroidID` crashing

### ISSUE THREAD

**Issue by milesj** [AppsFlyerSDK/appsflyer-react-native-plugin#179]
# Report

## Plugin Version

6.0.20

## On what Platform are you having the issue?

Android SDK 29
React Native 0.62

## What did you do?

When initializing the SDK, I attempt to call `setCollectAndroidID`.

```js
appsFlyer.initSdk(
  {
    devKey,
    isDebug: false,
  },
  (result) => {
    if (Platform.OS === 'android') {
      appsFlyer.setCollectAndroidID(true);
    }
  },
  (error) => {
    captureError(error);
  },
);
```

## What did you expect to happen?

Not to crash.

## What happened instead?

Crashes the app on launch.

```
2020-09-03 16:32:50.374 28688-28752/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: <app>, PID: 28688
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at com.appsflyer.reactnative.RNAppsFlyerModule.setCollectAndroidID(RNAppsFlyerModule.java:317)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by af-vs** [comment]
Hi @milesj!

Thanks for reporting the issue! Indeed some of the callbacks that were marked as options in fact were required. We have changed that in 6.0.30 (will be released shortly today), so setCollectAndroidID(true) should work now without any callbacks

However, please note, that it is only applicable to Android. On iOS React Native doesn't seem to support Nullable RCTResponseSenderBlock that we use for callbacks mechanisms.

**Comment by milesj** [comment]
Thanks so much!
