### ISSUE TITLE
Android NoClassDefFoundError: Failed resolution of: Lcom/appsflyer/AppsFlyerConversionListener

### ISSUE THREAD

**Issue by MasterChenGitHub** [AppsFlyerSDK/appsflyer-react-native-plugin#318]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
6.3.50

## On what Platform are you having the issue?
 android

## What did you do?

react-native run-android

## What did you expect to happen?
not crash

## What happened instead?
crash

## Please provide any other relevant information.

2021-08-31 16:47:28.089 20280-20394/? E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2021-08-31 16:47:28.274 20280-20393/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.**** PID: 20280
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appsflyer/AppsFlyerConversionListener;
        at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
        at java.lang.reflect.Method.getReturnType(Method.java:148)
        at java.lang.Class.getDeclaredMethods(Class.java:1880)
        at com.facebook.react.bridge.JavaModuleWrapper.findMethods(JavaModuleWrapper.java:78)
        at com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors(JavaModuleWrapper.java:109)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:210)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appsflyer.AppsFlyerConversionListener" on path: DexPathList[[zip

**Comment by amit-kremer93** [comment]
Hi @MasterChenGitHub and thank you for opening this issue. Do you have this crash on older versions of the plugin? when does this crash happen?

**Comment by MasterChenGitHub** [comment]
> Hi @MasterChenGitHub and thank you for opening this issue. Do you have this crash on older versions of the plugin? when does this crash happen?
New to integrate this plugin,crash just  after app launched.
Crash Errors:
Error: Exception in HostObject::get(propName:RNAppsFlyer): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appsflyer/AppsFlyerConversionListener

**Comment by MasterChenGitHub** [comment]
package.json
    "react-native-appsflyer": "^6.3.50",
settings.gradle
include ':react-native-appsflyer'
project(':react-native-appsflyer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-appsflyer/android')

build.gradle
    implementation project(':react-native-appsflyer')
    implementation 'com.appsflyer:af-android-sdk:6.3.2'

App.js
import appsFlyer from 'react-native-appsflyer';
// eslint-disable-next-line no-unused-vars
let onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
    (res) => {
      console.log('onInstallConversionData: ' + JSON.stringify(res));
      if (res.type === 'onInstallConversionSuccess') {
        if (JSON.parse(res.data.is_first_launch) === true) {
          if (res.data.af_status === 'Non-organic') {
            var media_source = res.data.media_source;
            var campaign = res.data.campaign;
            console.log(
                'This is first launch and a Non-Organic install. Media source: ' +
                media_source +
                ' Campaign: ' +
                campaign,
            );
          } else if (res.data.af_status === 'Organic') {
            console.log('This is first launch and a Organic Install');
          }
        } else {
          console.log('This is not first launch');
        }
      }
    },
);

// eslint-disable-next-line no-unused-vars
let onAppOpenAttributionCanceller = appsFlyer.onAppOpenAttribution((res) => {
  console.log(res);
});
appsFlyer.initSdk(
    {
      devKey: '***',
      isDebug: false,
      appId: '***',
      onInstallConversionDataListener: true, //Optional
      onDeepLinkListener: true, //Optional
      timeToWaitForATTUserAuthorization: 10 //for iOS 14.5
    },
    (result) => {
      console.log("chenzhenfeng",result);

    },
    (error) => {
      console.error(error);
    }
);

**Comment by MasterChenGitHub** [comment]
fixed:
The problem is android plugin :
apply plugin: 'android-aspectjx'
aspectjx {
   'com.appsflyer'
}
