### ISSUE TITLE
java.lang.IllegalAccessException

### ISSUE THREAD

**Issue by dnvarun** [AppsFlyerSDK/appsflyer-react-native-plugin#464]
# Report

## Plugin Version

6.9.4

## On what Platform are you having the issue?

android

## What did you do?

Called appsFlyer.logEvent

## What did you expect to happen?

Event to be logged successfully

## What happened instead?

logEvent failed and called error callback with the following stack trace
```
Fatal Exception: java.lang.Error: java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFa1zSDK$$.valueOf(:100)
       at com.appsflyer.internal.AFa1zSDK$$.AFKeystoreWrapper(:20)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFa1wSDK.values(:125)
       at com.appsflyer.internal.AFc1vSDK.AFKeystoreWrapper(:143)
       at com.appsflyer.internal.AFd1rSDK.AFKeystoreWrapper(:65)
       at com.appsflyer.internal.AFd1vSDK.values(:113)
       at com.appsflyer.internal.AFc1gSDK$1.run(:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

## Please provide any other relevant information.

Till now noticed this issue on Android 8.1.0

**Comment by amit-kremer93** [comment]
@dnvarun do you still see this exception?

**Comment by renanbronchart** [comment]
<img width="331" alt="Capture d’écran 2023-06-05 à 22 52 57" src="https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/16922579/111a2301-1b03-44d6-b723-626466a20271">

**Comment by renanbronchart** [comment]
> @dnvarun do you still see this exception?

Yes this exception is still present on production and it's a dealbreaker because it's a fatal error fo my customers.
Please can you help us on this exception?

**Comment by dnvarun** [comment]
@amit-kremer93 yes we still see it

**Comment by sregg** [comment]
We're seeing this too.

**Comment by dnvarun** [comment]
Any update on this?

**Comment by lhreska** [comment]
https://github.com/AppsFlyerSDK/appsflyer-android-app/issues/20#issuecomment-1644473907
seems that the fix will come at the next week

**Comment by aditya-keri-betterhalf** [comment]
@lhreska 
That fix will come to Android SDK first.
But this `react-native-appsflyer` package is still at 6.10.3. It's lagging behind by [5 versions](https://support.appsflyer.com/hc/en-us/articles/115001256006-AppsFlyer-Android-SDK-release-notes).

Can someone from the dev team please respond regarding a tentative timeline for this fix for react native ?

**Comment by amit-kremer93** [comment]
@aditya-keri-betterhalf new version is going to be released in the next few days

**Comment by aditya-keri-betterhalf** [comment]
@amit-kremer93 
Could you please confirm if this new version is going to be `6.12.2` ?
Because that's the one containing the fix for this issue.

**Comment by amit-kremer93** [comment]
No. it contains [6.12.1](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/CHANGELOG.md#6121)

**Comment by aditya-keri-betterhalf** [comment]
@amit-kremer93 
Thank you for replying again.
Any tentative timeline on releasing `6.12.2` so that we can get rid of this issue ?

**Comment by DevenHurt** [comment]
I'm having this issue as well. It looks like I can't upgrade to 6.12.2 yet.
